// Hierarchical key factory so `invalidateQueries({ queryKey: queryKeys.posts() })` cascades to
// every more-specific key below it (TanStack Query matches by array prefix).
export const queryKeys = {
  feed: () => ['feed'] as const,
  explore: () => ['explore'] as const,
  reelsFeed: () => ['reelsFeed'] as const,
  posts: () => ['posts'] as const,
  post: (id: number) => [...queryKeys.posts(), id] as const,
  userPosts: (username: string) => [...queryKeys.posts(), 'byUser', username] as const,
  savedPosts: () => [...queryKeys.posts(), 'saved'] as const,
  comments: (postId: number) => ['comments', postId] as const,
  users: () => ['users'] as const,
  userProfile: (username: string) => [...queryKeys.users(), username] as const,
  suggestions: () => [...queryKeys.users(), 'suggestions'] as const,
  followRequests: () => [...queryKeys.users(), 'followRequests'] as const,
  blockedUsers: () => [...queryKeys.users(), 'me', 'blocked'] as const,
  mutedUsers: () => [...queryKeys.users(), 'me', 'muted'] as const,
  insights: () => [...queryKeys.users(), 'me', 'insights'] as const,
  followers: (username: string) => [...queryKeys.users(), username, 'followers'] as const,
  following: (username: string) => [...queryKeys.users(), username, 'following'] as const,
  stories: () => ['stories'] as const,
  storiesFeed: () => [...queryKeys.stories(), 'feed'] as const,
  userStories: (username: string) => [...queryKeys.stories(), 'byUser', username] as const,
  highlights: (username: string) => [...queryKeys.stories(), 'highlights', username] as const,
  highlightDetail: (id: number) => [...queryKeys.stories(), 'highlights', 'detail', id] as const,
  notifications: () => ['notifications'] as const,
  conversations: () => ['conversations'] as const,
  // Deliberately NOT nested under conversations(): invalidating the inbox shouldn't refetch these
  // (and vice versa) — the handlers invalidate both explicitly when a request changes state.
  messageRequests: () => ['messageRequests'] as const,
  messageRequestCount: () => ['messageRequests', 'count'] as const,
  conversation: (id: number) => [...queryKeys.conversations(), id] as const,
  messages: (conversationId: number) => [...queryKeys.conversation(conversationId), 'messages'] as const,
  hashtag: (tag: string) => ['hashtags', tag] as const,
  hashtagPosts: (tag: string) => ['hashtags', tag, 'posts'] as const,
  searchHashtags: (q: string) => ['search', 'hashtags', q] as const,
  searchUsers: (q: string) => ['search', 'users', q] as const,
  searchPosts: (q: string) => ['search', 'posts', q] as const,
}
